# Generated by Django 4.2.5 on 2023-09-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'ユーザ', 'verbose_name_plural': 'ユーザ'},
        ),
    ]
