# Generated by Django 4.2.5 on 2023-09-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsuke', '0002_rename_purchase_date_tsuke_purchase_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tsuke',
            options={'verbose_name': 'ツケ', 'verbose_name_plural': 'ツケ'},
        ),
    ]
