# Generated by Django 4.2.5 on 2023-09-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuke', '0003_alter_tsuke_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsuke',
            name='category',
            field=models.CharField(choices=[('drink', '飲み物'), ('snack', 'お菓子'), ('cup_noodle', 'カップ麺'), ('others', 'その他')], default='drink', max_length=50, verbose_name='品目'),
        ),
    ]
