# Generated by Django 4.2.5 on 2023-09-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsuke', '0006_itemcategory_alter_tsuke_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name': '品目', 'verbose_name_plural': '品目'},
        ),
        migrations.RenameField(
            model_name='tsuke',
            old_name='purchase_datetime',
            new_name='purchase_date',
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='category',
            field=models.CharField(max_length=100, verbose_name='品目名'),
        ),
    ]
