# Generated by Django 4.2.5 on 2023-09-24 03:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tsuke", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tsuke",
            unique_together={("user", "purchase_date", "amount", "category")},
        ),
    ]
