# Generated by Django 4.2.5 on 2023-09-24 04:51

from django.db import migrations, models
import tsuke.models


class Migration(migrations.Migration):
    dependencies = [
        ("tsuke", "0002_alter_tsuke_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tsuke",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[tsuke.models.positive_validator], verbose_name="金額"
            ),
        ),
    ]
