# Generated by Django 4.2.6 on 2023-10-07 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tsuke", "0003_alter_tsuke_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tsuke",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザ",
            ),
        ),
    ]
