# Generated by Django 4.2.6 on 2023-10-07 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tsuke", "0004_alter_tsuke_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tsuke",
            name="payment_date",
            field=models.DateTimeField(auto_now=True, verbose_name="清算日時"),
        ),
        migrations.AlterField(
            model_name="tsuke",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tsuke.itemcategory",
                verbose_name="品目",
            ),
        ),
    ]
