# Generated by Django 4.2.6 on 2023-10-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tsuke", "0006_alter_tsuke_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tsuke",
            name="payment_date",
            field=models.DateTimeField(null=True, verbose_name="清算日時"),
        ),
    ]
