# Generated by Django 4.2.6 on 2024-02-10 02:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tsuke", "0007_alter_tsuke_payment_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="TsukeTotal",
            fields=[],
            options={
                "verbose_name": "ツケ合計",
                "verbose_name_plural": "ツケ合計",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tsuke.tsuke",),
        ),
    ]
