# Generated by Django 4.2.6 on 2024-02-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tsuke", "0008_tsuketotal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tsuketotal",
            options={"verbose_name": "集計", "verbose_name_plural": "集計"},
        ),
        migrations.AlterField(
            model_name="tsuke",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="清算"),
        ),
    ]
