# Inherited from:
# https://github.com/actions/starter-workflows/blob/main/ci/django.yml
# https://qiita.com/shun198/items/65025b5cc5729b4217e1

name: Django CI

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main

env:
  DJANGO_SETTINGS_MODULE: tsukepp.settings_test
  ALLOWED_HOSTS: 127.0.0.1
  # "True"にしないとDEBUG内がFalseになってしまう
  DEBUG: "True"
  POSTGRES_NAME: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: 127.0.0.1
  POSTGRES_PORT: 5432

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]
    services:
      db:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_NAME: ${{ env.POSTGRES_NAME }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        # Postgresより先にDjangoが起動しないようヘルスチェックを使って起動順を制御
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"  # https://github.com/actions/setup-python?tab=readme-ov-file#caching-packages-dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Migrate
      run: |
        python manage.py makemigrations --settings ${{ env.DJANGO_SETTINGS_MODULE }}
        python manage.py migrate --settings ${{ env.DJANGO_SETTINGS_MODULE }}
    - name: Run Tests
      run: |
        python manage.py test tsuke.tests --settings ${{ env.DJANGO_SETTINGS_MODULE }}
